// THIS FILE IS AUTO-GENERATED by `pnpm generate`. DO NOT EDIT MANUALLY.
import type { ComponentType } from "react"
import {
  BannerCategoryPreview,
  CtaCategoryPreview,
  FaqCategoryPreview,
  FooterCategoryPreview,
  GenericCategoryPreview,
  HeroCategoryPreview,
  LoginCategoryPreview,
  SidebarCategoryPreview,
  SocialProofCategoryPreview,
  type BlockCategoryPreviewProps,
} from "@/components/block-category-previews"

export const blockCategoryPreviewMap: Record<string, ComponentType<BlockCategoryPreviewProps>> = {
  "banner": BannerCategoryPreview,
  "cta": CtaCategoryPreview,
  "faq": FaqCategoryPreview,
  "footer": FooterCategoryPreview,
  "hero": HeroCategoryPreview,
  "login": LoginCategoryPreview,
  "sidebar": SidebarCategoryPreview,
  "social-proof": SocialProofCategoryPreview,
}

export function getBlockCategoryPreview(categorySlug: string): ComponentType<BlockCategoryPreviewProps> {
  return blockCategoryPreviewMap[categorySlug] ?? GenericCategoryPreview
}
